<?php

namespace ContainerUI5NhQt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Lazy_DataCollector_DumpService extends App_KernelDevContainer
{
    /*
     * Gets the private '.lazy.data_collector.dump' shared service.
     *
     * @return \Symfony\Component\HttpKernel\DataCollector\DumpDataCollector
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['.lazy.data_collector.dump'] = $container->createProxy('DumpDataCollectorProxy3957579', static fn () => \DumpDataCollectorProxy3957579::createLazyProxy(static fn () => self::do($container, false)));
        }

        return ($container->services['data_collector.dump'] ?? self::getDataCollector_DumpService($container));
    }
}
