<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCMQQ3Qy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCMQQ3Qy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCMQQ3Qy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCMQQ3Qy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCMQQ3Qy\App_KernelDevDebugContainer([
    'container.build_hash' => 'CMQQ3Qy',
    'container.build_id' => '04c109cb',
    'container.build_time' => 1790692559,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCMQQ3Qy');
