<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUI5NhQt\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUI5NhQt/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerUI5NhQt.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerUI5NhQt\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerUI5NhQt\App_KernelDevContainer([
    'container.build_hash' => 'UI5NhQt',
    'container.build_id' => '9517260f',
    'container.build_time' => 1790693449,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUI5NhQt');
